services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: rootpassword
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgres/data
volumes:
    pgdata:
        driver: local
